# Generated by Django 5.0.2 on 2024-02-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('Islamabad', 'Islamabad'), ('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Azad Jammu and Kashmir', 'Azad Jammu and Kashmir')], max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(blank=True, upload_to='images')),
                ('file', models.FileField(blank=True, upload_to='files')),
            ],
        ),
    ]
